In [72]:
#Importing numpy
import numpy as np

In [73]:
#Initializing the first array
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

In [74]:
a < 0

array([False, False, False, False,  True,  True, False, False, False,
        True, False,  True])

In [75]:
a_mask = a < 0
a_mask

array([False, False, False, False,  True,  True, False, False, False,
        True, False,  True])

In [76]:
a[a_mask]

array([-2, -1, -6, -7])

In [77]:
#How many negative numbers are there
len(a[a < 0])

4

In [78]:
a[a < 0].shape

(4,)

In [79]:
#How many positive numbers are there
pos_num = a[a > 0]

In [80]:
#How many even positive numbers are there
pos_and_even = pos_num[pos_num % 2 == 0]

len(pos_and_even)

3

In [81]:
#If you added 3 to each data point, how many positive numbers would there be?
sum_3 = a[(a + 3) > 0]

len(sum_3)

10

In [46]:
#If you squared each number, what would the new mean and standard deviation be?
squared_a = a ** 2
print('The new mean is {}.'.format(squared_a.mean()))
print('The new standard deviation is {}.'.format(squared_a.std()))

The new mean is 74.0.
The new standard deviation is 144.0243035046516.


In [70]:
#Center the original dataset by subtracting the mean from each data point
centered_a = a - a.mean()

centered_a.mean()

0.0

In [71]:
#Calculate the z scores for each data point
z_scores = centered_a / a.std()
z_scores

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

In [49]:
#Forming the list for the first few exercises
a = list(range(1, 11))

In [50]:
#Assigning the proper value to each variable using the base python library
sum_of_a = sum(a)
print('Sum of a: {}'.format(sum_of_a))

min_of_a = min(a)
print('Min of a: {}'.format(min_of_a))

max_of_a = max(a)
print('Max of a: {}'.format(max_of_a))

mean_of_a = sum_of_a / len(a)
print('Mean of a: {}'.format(mean_of_a))

product_of_a = 1
for num in a:
    product_of_a *= num

print('Product of a: {}'.format(product_of_a))

squares_of_a = [num ** 2 for num in a]
print('Squares of a: {}'.format(squares_of_a))

odds_in_a = [num for num in a if num % 2 == 1]
print('Odds in a: {}'.format(odds_in_a))

evens_in_a = [num for num in a if num % 2 == 0]
print('Evens in a: {}'.format(evens_in_a))

Sum of a: 55
Min of a: 1
Max of a: 10
Mean of a: 5.5
Product of a: 3628800
Squares of a: [1, 4, 9, 16, 25, 36, 49, 64, 81, 100]
Odds in a: [1, 3, 5, 7, 9]
Evens in a: [2, 4, 6, 8, 10]


In [51]:
#Initializing the second array
b = np.array([[3, 4, 5],
              [6, 7, 8]])
b

array([[3, 4, 5],
       [6, 7, 8]])

In [52]:
#Assigning the proper value to each variable using the numpy library
sum_of_b = np.sum(b)
print('Sum of b: {}.'.format(sum_of_b))

min_of_b = np.min(b)
print('Min of b: {}.'.format(min_of_b))

max_of_b = np.max(b)
print('Max of b: {}.'.format(max_of_b))

mean_of_b = np.mean(b)
print('Mean of b: {}.'.format(mean_of_b))

product_of_b = np.product(b)
print('Product of b: {}.'.format(product_of_b))

squares_of_b = np.square(b)
print('Squares of b:\n{}.'.format(squares_of_b))

odds_in_b = b[b % 2 == 1]
print('Odds in b: {}.'.format(odds_in_b))

evens_in_b = b[b % 2 == 0]
print('Evens in b: {}.'.format(evens_in_b))

print('Shape of b: {}.'.format(b.shape))

print('b transposed:\n{}.'.format(b.transpose()))

print('b reshaped to (1, 6): {}.'.format(b.reshape((1, 6))))

print('b reshaped to (6, 1):\n{}.'.format(b.reshape((6, 1))))

Sum of b: 33.
Min of b: 3.
Max of b: 8.
Mean of b: 5.5.
Product of b: 20160.
Squares of b:
[[ 9 16 25]
 [36 49 64]].
Odds in b: [3 5 7].
Evens in b: [4 6 8].
Shape of b: (2, 3).
b transposed:
[[3 6]
 [4 7]
 [5 8]].
b reshaped to (1, 6): [[3 4 5 6 7 8]].
b reshaped to (6, 1):
[[3]
 [4]
 [5]
 [6]
 [7]
 [8]].


In [53]:
#Creating a new array for the next set of exercises
c = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

In [54]:
#Determing the min, max, sum, and product of c
print(c.min())

print(c.max())

print(c.sum())

print(c.prod())

1
9
45
362880


In [55]:
#Some math operations with a 2d matrix
print('Standard deviation of c: {}.'.format(c.std()))

print('Variance of c: {}.'.format(c.var()))

print('Shape of c: {}.'.format(c.shape))

print('c transposed:\n{}.'.format(c.transpose()))

print('Dot product of c with c:\n{}.'.format(np.dot(c, c)))

print('Sum of c times c transposed: {}.'.format(np.sum(c * c.transpose())))

print('Product of c times c transposed: {}.'.format(np.product(c * c.transpose())))

Standard deviation of c: 2.581988897471611.
Variance of c: 6.666666666666667.
Shape of c: (3, 3).
c transposed:
[[1 4 7]
 [2 5 8]
 [3 6 9]].
Dot product of c with c:
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]].
Sum of c times c transposed: 261.
Product of c times c transposed: 131681894400.


In [56]:
#Defining a new array for the final set of exercises
d = np.array([[90, 30, 45, 0, 120, 180],
              [45, -90, -30, 270, 90, 0],
              [60, 45, -45, 90, -45, 180]])

In [57]:
print('Sin values of d:\n{}.\n\n'.format(np.sin(d)))

print('Cos values of d:\n{}.\n\n'.format(np.cos(d)))

print('Tan values of d:\n{}.\n\n'.format(np.tan(d)))

print('Negative numbers in d: {}.\n'.format(d[d < 0]))

print('Positive numbers in d: {}.\n'.format(d[d > 0]))

print('Unique numbers in d: {}.\n'.format(np.unique(d)))

print('Shape of d: {}.\n'.format(np.shape(d)))

print('d transposed:\n{}.\n'.format(np.transpose(d)))

print('d reshaped to (9, 2):\n{}.'.format(np.reshape(d, (9, 2))))

Sin values of d:
[[ 0.89399666 -0.98803162  0.85090352  0.          0.58061118 -0.80115264]
 [ 0.85090352 -0.89399666  0.98803162 -0.17604595  0.89399666  0.        ]
 [-0.30481062  0.85090352 -0.85090352  0.89399666 -0.85090352 -0.80115264]].


Cos values of d:
[[-0.44807362  0.15425145  0.52532199  1.          0.81418097 -0.59846007]
 [ 0.52532199 -0.44807362  0.15425145  0.98438195 -0.44807362  1.        ]
 [-0.95241298  0.52532199  0.52532199 -0.44807362  0.52532199 -0.59846007]].


Tan values of d:
[[-1.99520041 -6.4053312   1.61977519  0.          0.71312301  1.33869021]
 [ 1.61977519  1.99520041  6.4053312  -0.17883906 -1.99520041  0.        ]
 [ 0.32004039  1.61977519 -1.61977519 -1.99520041 -1.61977519  1.33869021]].


Negative numbers in d: [-90 -30 -45 -45].

Positive numbers in d: [ 90  30  45 120 180  45 270  90  60  45  90 180].

Unique numbers in d: [-90 -45 -30   0  30  45  60  90 120 180 270].

Shape of d: (3, 6).

d transposed:
[[ 90  45  60]
 [ 30 -90  45]
 [ 45 -30 